//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class IdleState:IState
{
	private float IdleTime = 0f;
	
	public IdleState (Boss boss) : base(StateIds.Idle, boss)
	{
		NextStateIds.Add(StateIds.Attacking);
	}
	
	public override int ChangeState (float deltaTime)
	{
		int newStateId = StateId;
		
		if(boss.Hurt)
			return StateIds.Hurt;
			
		if(boss.StunHP < 0)
			return StateIds.Stunned;
		
		if(IdleTime <= 0)
		{
			newStateId = StateIds.Attacking;
		}
		return newStateId;
	}
	
	public override void ProcessState (float deltaTime)
	{
		IdleTime -= deltaTime;
		//play idle animation
	}
	
	public override void Setup ()
	{
		IdleTime = boss.IdleTime;
		//tell boss the idle was handled
		boss.HandleRecovery();
	}
	
	public override void SerializeNetwork (UnityEngine.BitStream stream)
	{
		float _idleTime = IdleTime;
		if(stream.isWriting)
		{
			stream.Serialize(ref _idleTime);
		}
		else{
			stream.Serialize(ref _idleTime);
			IdleTime = _idleTime;
		}
	}
}


